name: Deploy Angular to VPS (Apache)

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar cÃ³digo
      - uses: actions/checkout@v4

      # 2. Instalar Node
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Instalar dependencias y compilar
      - run: npm ci
      - run: npm run build -- --configuration production
      - name: Listar archivos generados (Debug)
        run: ls -R dist

      # 4. Crear .htaccess dentro de la carpeta browser
      - name: Create .htaccess
        run: |
          cat > dist/series-pruebafebpvsl/browser/.htaccess <<EOF
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          EOF

      # 5. Desplegar al VPS
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: dist/series-pruebafebpvsl/browser/
          remote_path: ${{ secrets.VPS_PATH }}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}